* Protocheck
Protocheck is an application designed to verify various correctness properties of protocols defined in the BSPL family of languages.

** Installation
   Protocheck may eventually be made available through the PyPI package registry, but for now install it directly from github.

*** github
    1. Download the source code from github:
       #+begin_example
       $ git clone https://github.com/shader/protocheck.git
       #+end_example
    2. Optionally create virtualenv for protocheck
       #+begin_example
       $ mkvirtualenv protocheck
       #+end_example
    3. Install package globally
       #+begin_example
       $ sudo pip install ./protocheck
       #+end_example
    
** Usage
   When installed globally, protocheck provides the 'bspl' entrypoint, that can be used as follows:

   #+begin_example
usage: bspl [-h] [-t] [-e] [-d DEPTH] [-s] [-v] [-q] [-f FILTER]
            {safety,enactability,liveness,atomicity,all} input [input ...]

BSPL Protocol property checker

positional arguments:
  {safety,enactability,liveness,atomicity,all}
                        Primary action to perform
  input                 Protocol description file(s)

optional arguments:
  -h, --help            show this help message and exit
  -t, --tseytin
  -e, --exhaustive
  -d DEPTH, --depth DEPTH
                        Longest transitive relationship to generate. Only need
                        log2(max-chain) to prevent cycles. (default: 1)
  -s, --stats           Print statistics (default: False)
  -v, --verbose         Print additional details: spec, formulas, stats, etc.
                        (default: False)
  -q, --quiet           Prevent printing of violation and formula output
                        (default: False)
  -f FILTER, --filter FILTER
                        Only process protocols matching regexp (default: .*)
   #+end_example

   'input' is the filename of a protocol specification file.

   There are some example protocol files in the 'samples' directory.

** Notes
   - The default heuristics for protocol verification are not always correct. If you are unsure of the answer, try again with '--exhaustive'.
   - There are probably still some bugs. If you find a case that doesn't work as you expect, please record everything with '-v' and submit an issue.
   - For easier testing of listings used in latex papers, protocheck will automatically strip latex formatting before parsing a protocol, so they should work without modification.
